title: Blockchainnewbie goes coding!
author: Sonny Ram 
email: moptix@tuta.io
description: > # this means to ignore newlines until "baseurl:"
  This is my first Github project on the way to becoming a full time Blockchain developer. 
  I will teach myself and my goal is to someday program for IOHK / Cardano with Haskell.
# social links
twitter_username: @coinimoon
github_username:  Blockchainewbie

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
